# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclid <- function(p1, p2) {
    .Call('ggrepel_euclid', PACKAGE = 'ggrepel', p1, p2)
}

put_within_bounds <- function(b, xlim, ylim) {
    .Call('ggrepel_put_within_bounds', PACKAGE = 'ggrepel', b, xlim, ylim)
}

centroid <- function(b) {
    .Call('ggrepel_centroid', PACKAGE = 'ggrepel', b)
}

#' Test if a box overlaps another box.
overlaps <- function(a, b) {
    .Call('ggrepel_overlaps', PACKAGE = 'ggrepel', a, b)
}

#' Test if a point is within the boundaries of a box.
point_within_box <- function(p, b) {
    .Call('ggrepel_point_within_box', PACKAGE = 'ggrepel', p, b)
}

#' Compute the force upon point a from point b.
compute_force <- function(a, b, force = 0.000001) {
    .Call('ggrepel_compute_force', PACKAGE = 'ggrepel', a, b, force)
}

#' Adjust the layout of a list of potentially overlapping boxes.
repel_boxes <- function(boxes, xlim, ylim, force = 1e-6, maxiter = 1e4L) {
    .Call('ggrepel_repel_boxes', PACKAGE = 'ggrepel', boxes, xlim, ylim, force, maxiter)
}

